pipeline:
  build:
    image: node:8.11.3-alpine
    commands:
      - npm install
      - npm test

  ssh-deploy:
    image: appleboy/drone-ssh
    pull: true  # always pull the latest version of the `drone-ssh` plugin
    username: yedda
    password:
      from_secret: ssh_password
    host: 192.168.2.98
    port: 22
    command_timeout: 180s
    script:
      - echo ${DRONE_COMMIT}
      - cd /home/yedda/deploy
      - sh deploy.sh ${DRONE_COMMIT}
    when:
      event: [push, tag, deployment]
      
  slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: docker
    template: >
      {{#success build.status}}
        Hello, build {{build.number}} commit {{build.commit}} succeeded. Good job.
      {{else}}
        Sorry, build {{build.number}} commit {{build.commit}} failed. Fix me please.
      {{/success}}